"""add violation table

Revision ID: 2f323b4e995a
Revises: 73c4bc3ae01a
Create Date: 2022-01-30 15:49:57.139761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f323b4e995a'
down_revision = '73c4bc3ae01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('comments', sa.String(length=2048), nullable=False),
    sa.Column('is_corrected_on_site', sa.Boolean(), nullable=True),
    sa.Column('is_repeat', sa.Boolean(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.inspection_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation')
    # ### end Alembic commands ###
