"""add restaurant table

Revision ID: 73c4bc3ae01a
Revises: cda95632f676
Create Date: 2022-01-30 15:46:56.004950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c4bc3ae01a'
down_revision = 'cda95632f676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('street_address', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('insert_timestamp', sa.DateTime(), nullable=False),
    sa.Column('cuisine_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.add_column('inspection', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inspection', 'restaurant', ['restaurant_id'], ['restaurant_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.drop_column('inspection', 'restaurant_id')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
