"""inspections table

Revision ID: cda95632f676
Revises: 
Create Date: 2022-01-30 15:19:59.649100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda95632f676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=2048), nullable=True),
    sa.Column('insert_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection')
    # ### end Alembic commands ###
